name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    #- name: Run Tests
    #  run: bash ./gradlew test --stacktrace

    # - name: Build with Gradle
    #   run: ./gradlew clean build
    - name: Build APK
      run: ./gradlew build 

    - name: Extra Step - look about for artifacts
      run: |
        cd app/build/outputs/apk
        ls -la

    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: CocoaWallet.apk
        path: app/build/outputs/apk/debug/app-debug.apk
        
        
        

    # - name: Upload APK Artifact GitHub Action
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: apk
    #     path: build/outputs/apk



