name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: 1. Check out this branch
      uses: actions/checkout@v1

    - name: 2. set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        distribution: 'adopt'
        cache: gradle

    - name: 3. Set up files
      run: |
        # 'here is where we should copy and rename files to somewhere they will install'
        cd ${{github.workspace}}/app/src/main/assets/arm64-v8a/
        cp xmrig ${{github.workspace}}/app/libs/libminer.so
        cp libuv ${{github.workspace}}/app/libs/libuv.so

    - name: 4. Build APK
      run: |
        chmod +x gradlew
        bash ./gradlew build --stacktrace

    - name: 5. Sign Android release custom
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      # You may pin to the exact commit or the version.
      # uses: thomastvedt/sign-android-release@c2d33f93261f0f313de00a41c032c30d5fb843a6
      uses: thomastvedt/sign-android-release@v2.2
      with:
        # The directory to find your release to sign
        releaseDirectory: 'app/build/outputs/apk/release'
        # The key used to sign your release in base64 encoded format
        signingKeyBase64: ${{ secrets.SIGNING_KEY_B64 }}
        # The key alias
        alias: ${{ secrets.KEY_ALIAS }}
        # The password to the keystore
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        # The password for the key
        keyPassword: ${{ secrets.KEY_PASSWORD }}
        # optional

    - name: 6. Poke about about for artifacts
      run: |
        cd app/build/outputs/apk/release
        mv app-release-unsigned-signed.apk CocoaWallet.apk
        ls -la

    - name: 7. Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: CocoaWallet
        # path: app/build/outputs/apk/debug/app-debug.apk
        path: app/build/outputs/apk/release/CocoaWallet.apk



